### ISSUE TITLE
Doesn't seem to be working 

### ISSUE THREAD

**Issue by chuckster67** [PatriotDevOps/Infowars-Live-App#1]
The icons for the feeds disappeared

**Comment by chuckster67** [comment]
![20191118_165303](https://user-images.githubusercontent.com/57759751/69103934-f5ab5180-0a23-11ea-9c3a-cb56e0792c35.jpg)

**Comment by eliteprox** [comment]
There was a server issue around November 2019 and I had to change domains. Version 2.0 does not work anymore. 

If you installed it prior to June 2019, upgrade it to 2.1 using this zip file: https://github.com/PatriotDevOps/Infowars-Live-App/releases/tag/7a747a4

I hope this helps, let me know and I’ll close this if it’s working now.

**Comment by eliteprox** [comment]
Known issue from the time, has been resolved with an update to 2.1.

**Comment by yoyo2312** [comment]
I have 2.1 and this is happening for me as well.
